name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        env:
          AWS_REGION: ap-south-1    # Update to the region where you want to deploy your Lambda function
          AWS_LAMBDA_FUNCTION_NAME: my-node-server-lambda    # Update to the name of your AWS Lambda function
          AWS_PROFILE: my-aws-profile    # Update to the name of your AWS CLI profile
        run: |
          npm run build    # If you need to build your Node.js server before deploying it
          sls deploy    # Use the Serverless Framework to deploy your Node.js server to AWS Lambda